# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhprAT04 < Formula
  desc "Creates a pull request on GitHub setting the PR title to JIRA issue title"
  homepage "https://jmoney.dev/create-pr-from-jira"
  version "0.4"
  license "Apache 2.0"

  on_macos do
    on_intel do
      url "https://github.com/jmoney/create-pr-from-jira/releases/download/0.4/ghpr_0.4_darwin_amd64.tar.gz"
      sha256 "3d77c2ba082b8ab5ea8a2fe14ae60286af772501da7a45cc9c8ef0a926c7a565"

      def install
        bin.install "ghpr"
      end
    end
    on_arm do
      url "https://github.com/jmoney/create-pr-from-jira/releases/download/0.4/ghpr_0.4_darwin_arm64.tar.gz"
      sha256 "f263825f27c1d9006627bc83e6d297e69ad9a445a228ec55395a0e4043878c54"

      def install
        bin.install "ghpr"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jmoney/create-pr-from-jira/releases/download/0.4/ghpr_0.4_linux_amd64.tar.gz"
        sha256 "8472331c1d081eaa6b1f36484c061e6fcc492bd7c9e3afeddf77ecef42c32ff6"

        def install
          bin.install "ghpr"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jmoney/create-pr-from-jira/releases/download/0.4/ghpr_0.4_linux_arm64.tar.gz"
        sha256 "f14ae7140bdfc561041434649f13033d7cdc29fb7da2d78564d40fda944e9098"

        def install
          bin.install "ghpr"
        end
      end
    end
  end

  test do
    system "#{bin}/ghpr -h"
  end
end
