# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhprAT02 < Formula
  desc "Creates a pull request on GitHub setting the PR title to JIRA issue title"
  homepage "https://jmoney.dev/create-pr-from-jira"
  version "0.2"
  license "Apache 2.0"

  on_macos do
    on_intel do
      url "https://github.com/jmoney/create-pr-from-jira/releases/download/0.2/ghpr_0.2_darwin_amd64.tar.gz"
      sha256 "778e69b5384e703cdbf5b2f26ceac16d7b78801155e5ef5decaa88640511a6c7"

      def install
        bin.install "ghpr"
      end
    end
    on_arm do
      url "https://github.com/jmoney/create-pr-from-jira/releases/download/0.2/ghpr_0.2_darwin_arm64.tar.gz"
      sha256 "2841951446f392ce9c4a1095d408f46dcbf67a0e76a88d51a6637ffca008309d"

      def install
        bin.install "ghpr"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jmoney/create-pr-from-jira/releases/download/0.2/ghpr_0.2_linux_amd64.tar.gz"
        sha256 "c77cf0e34dfa9326806bb904e00191163ac30d147b0519544bc613599b9347bb"

        def install
          bin.install "ghpr"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jmoney/create-pr-from-jira/releases/download/0.2/ghpr_0.2_linux_arm64.tar.gz"
        sha256 "6ddc7c77baaf70d13f177861163784ae9c364bdf24979702cfe6738fee2df81c"

        def install
          bin.install "ghpr"
        end
      end
    end
  end

  test do
    system "#{bin}/ghpr -h"
  end
end
